browser=chrome
Bank_url= https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login

firstname1=John
lastname1=Chris
postcode1=12345678

firstname2=Michale
lastname2=Doe
postcode2=098765432

firstname3=Heaven
lastname3=Macdonald
postcode3=23456789


firstname4=Tony
lastname4=Rich
postcode4=987654321

firstname5=Queen
lastname5=James
postcode5=345678901

amount=100






